# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('bonus', 'Bono'), ('subscription', 'Suscripción'), ('product', 'Producto'), ('service', 'Servicio')], max_length=20)),
                ('concept', models.CharField(max_length=255)),
                ('reference_id', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tax_percentage', models.IntegerField(default=21)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('cancelled', 'Cancelado')], default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='gyms.gym')),
            ],
        ),
    ]
