# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_send_invoice', models.BooleanField(default=True)),
                ('invoice_email_optional_on_manual', models.BooleanField(default=True)),
                ('monthly_statement_day', models.IntegerField(default=1)),
                ('monthly_statement_emails', models.TextField(blank=True, help_text='Emails separados por coma')),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currencyconfig')),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gyms.franchise')),
            ],
        ),
        migrations.CreateModel(
            name='GymSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_send_invoice', models.BooleanField(blank=True, null=True)),
                ('invoice_email_optional_on_manual', models.BooleanField(blank=True, null=True)),
                ('monthly_statement_day', models.IntegerField(blank=True, null=True)),
                ('monthly_statement_emails', models.TextField(blank=True, null=True)),
                ('invoice_prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('next_invoice_number', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currencyconfig')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.franchise')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
