# Generated by Django 5.2.4 on 2025-08-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gyms', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('booking_created', 'Reserva creada'), ('booking_reminder', 'Recordatorio antes de clase'), ('booking_thanks', 'Post asistencia'), ('no_show', 'Ausencia del cliente'), ('subscription_expiring', 'Suscripción por vencer'), ('subscription_expired', 'Suscripción vencida'), ('new_client', 'Nuevo cliente'), ('birthday', 'Cumpleaños del cliente'), ('daily_report', 'Reporte diario al staff')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('hours_before', models.IntegerField(blank=True, null=True)),
                ('send_to_client', models.BooleanField(default=True)),
                ('send_to_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='gyms.gym')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.marketingtemplate')),
            ],
            options={
                'verbose_name': 'Regla de Notificación',
                'verbose_name_plural': 'Reglas de Notificación',
                'unique_together': {('gym', 'trigger')},
            },
        ),
    ]
