# Generated by Django 5.2.4 on 2025-08-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('intensity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('extreme', 'Extrema')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_reservation_notice', models.DurationField(help_text='Antelación mínima para reservar (ej: 1 day, 2:00:00 para 2 horas)')),
                ('min_cancellation_notice', models.DurationField(help_text='Antelación mínima para cancelar sin penalización')),
                ('open_reservation_hour', models.TimeField(blank=True, help_text='Hora diaria fija a partir de la cual se puede reservar (opcional)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
