# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_categories', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='activitysubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitysubcategory'),
        ),
    ]
