# Generated by Django 5.2.4 on 2025-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(default=20, help_text='Capacidad máxima de personas por clase'),
        ),
    ]
