# Generated by Django 5.2.4 on 2025-08-14 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0004_alter_franchise_slug_alter_gym_slug'),
        ('saas', '0002_module_stripe_product_id_moduleprice_stripe_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymStripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('default_payment_method_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Gym Stripe customer',
                'verbose_name_plural': 'Gym Stripe customers',
            },
        ),
        migrations.CreateModel(
            name='GymStripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', max_length=30)),
                ('cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='saas_payments.gymstripecustomer')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscriptions', to='gyms.gym')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymStripeSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_item_id', models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.module')),
                ('module_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.moduleprice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='saas_payments.gymstripesubscription')),
            ],
            options={
                'verbose_name': 'Subscription item',
                'verbose_name_plural': 'Subscription items',
            },
        ),
        migrations.AddConstraint(
            model_name='gymstripesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('gym',), name='uniq_active_stripe_subscription_per_gym'),
        ),
        migrations.AlterUniqueTogether(
            name='gymstripesubscriptionitem',
            unique_together={('subscription', 'module')},
        ),
    ]
