# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('bono', 'Bono')], max_length=50)),
                ('subcategory', models.CharField(choices=[('reformer', 'Reformer'), ('fitness', 'Fitness'), ('pilates', 'Pilates')], max_length=50)),
                ('plan_type', models.CharField(choices=[('subscription', 'Suscripción'), ('bonus', 'Bono')], default='subscription', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_day', models.IntegerField(default=1)),
                ('can_be_purchased_online', models.BooleanField(default=False)),
                ('enable_prorate', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('signup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_includes_tax', models.BooleanField(default=True)),
                ('tax_percentage', models.IntegerField(default=21)),
                ('allow_multiple_subscriptions', models.BooleanField(default=False)),
                ('html_embed_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('per_day', 'Por día'), ('per_week', 'Por semana'), ('per_month', 'Por mes'), ('total', 'Total fijo')], max_length=20)),
                ('limit_quantity', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_links', to='activities.activity')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='plans.plan')),
            ],
        ),
    ]
