# Generated by Django 5.2.4 on 2025-08-05 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('can_sell', models.BooleanField(default=False)),
                ('can_create_subs', models.BooleanField(default=False)),
                ('can_manage_clients', models.BooleanField(default=False)),
                ('can_see_finance', models.BooleanField(default=False)),
                ('can_book_classes', models.BooleanField(default=False)),
                ('uses_gym_schedule', models.BooleanField(default=True)),
                ('schedule_start', models.TimeField(blank=True, null=True)),
                ('schedule_end', models.TimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.franchise')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='gyms.gym')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
