# Generated by Django 5.2.4 on 2025-08-06 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_capacity'),
        ('staff', '0002_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regla', models.CharField(choices=[('fixed_monthly', 'Salario fijo mensual'), ('per_class', 'Pago por clase dictada'), ('per_service', 'Pago por servicio 1:1'), ('per_sale', 'Comisión por venta')], max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Filtrado opcional por franja horaria', null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('modo_pago', models.CharField(choices=[('fixed', 'Cantidad fija'), ('percent', 'Porcentaje')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Monto en euros o porcentaje', max_digits=7)),
                ('por_cliente_asistido', models.BooleanField(default=False, help_text='Aplica solo si el cliente asistió')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rules', to='staff.staff')),
            ],
        ),
    ]
