# Generated by Django 5.2.4 on 2025-08-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_salaryrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrule',
            options={'verbose_name': 'Regla Salarial', 'verbose_name_plural': 'Reglas Salariales'},
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='min_clientes_asistidos',
            field=models.PositiveIntegerField(blank=True, help_text='Mínimo de clientes que deben asistir para que se active la regla', null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='min_porcentaje_aforo',
            field=models.FloatField(blank=True, help_text='Porcentaje mínimo de aforo ocupado requerido (entre 0.0 y 1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='por_cliente_asistido',
            field=models.BooleanField(default=False, help_text='Aplicar el pago por cada cliente que asistió'),
        ),
    ]
