# Generated by Django 5.2.4 on 2025-08-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('staff', '0004_alter_salaryrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='gyms.gym'),
        ),
    ]
