# Generated by Django 5.2.4 on 2025-08-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('gyms', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('popup', 'Popup')], max_length=10)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.franchise')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('popup', 'Popup')], max_length=10)),
                ('sender_level', models.CharField(choices=[('superadmin', 'Superadmin'), ('franchise', 'Franchise'), ('gym', 'Gym')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('clients', 'Clientes'), ('staff', 'Staff'), ('both', 'Ambos')], default='clients', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.franchise')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.gym')),
                ('target_gyms', models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='gyms.gym')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.marketingcampaign')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('client__isnull', False), ('staff__isnull', False), _connector='OR'), name='at_least_one_recipient')],
            },
        ),
    ]
