# Generated by Django 5.2.4 on 2025-12-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del servicio (web/app cliente)', null=True, upload_to='services/'),
        ),
    ]
