# Generated by Django 5.2.4 on 2025-12-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='catalog_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'module': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.catalogcategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='catalog_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.catalogsubcategory'),
        ),
    ]
