# Generated by Django 5.2.4 on 2025-08-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
        ('gyms', '0005_gymmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_gym',
            field=models.ForeignKey(blank=True, help_text='Última sede activa del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='gyms.gym'),
        ),
    ]
