# Generated by Django 5.2.4 on 2025-08-14 08:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='franchise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='franchises/logos/'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='primary_color',
            field=models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color HEX válido, p. ej. #111827 o #06B6D4.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='franchise',
            name='secondary_color',
            field=models.CharField(default='#06B6D4', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color HEX válido, p. ej. #111827 o #06B6D4.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='country',
            field=models.CharField(default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='gym',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='locale',
            field=models.CharField(default='es-ES', max_length=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='timezone',
            field=models.CharField(default='Europe/Madrid', max_length=64),
        ),
        migrations.AddField(
            model_name='gym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franchises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='franchise',
            index=models.Index(fields=['owner'], name='gyms_franch_owner_i_bce4da_idx'),
        ),
        migrations.AddIndex(
            model_name='franchise',
            index=models.Index(fields=['is_active'], name='gyms_franch_is_acti_7a11a0_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['owner'], name='gyms_gym_owner_i_eb7aff_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['franchise'], name='gyms_gym_franchi_30dd28_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['is_active'], name='gyms_gym_is_acti_0fa45a_idx'),
        ),
    ]
