# Generated by Django 5.2.4 on 2025-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_backfill_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
