# Generated by Django 5.2.4 on 2025-08-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_franchise_slug_alter_gym_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=10)),
                ('can_manage_clients', models.BooleanField(default=False)),
                ('can_manage_cash', models.BooleanField(default=False)),
                ('can_manage_activities', models.BooleanField(default=False)),
                ('can_manage_bonuses', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='gyms_gymmem_user_id_51e0b7_idx'), models.Index(fields=['gym'], name='gyms_gymmem_gym_id_680c61_idx'), models.Index(fields=['role'], name='gyms_gymmem_role_69566b_idx'), models.Index(fields=['is_active'], name='gyms_gymmem_is_acti_3353cc_idx')],
                'unique_together': {('user', 'gym')},
            },
        ),
    ]
