# Generated by Django 5.2.4 on 2025-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='stripe_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moduleprice',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
