# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_modified', models.BooleanField(default=False)),
                ('signup_fee_applied', models.BooleanField(default=True)),
                ('was_prorated', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('limit_type', models.CharField(choices=[('per_day', 'Por día'), ('per_week', 'Por semana'), ('per_month', 'Por mes'), ('total', 'Total fijo')], max_length=20)),
                ('limit_quantity', models.PositiveIntegerField()),
                ('usage_log', models.JSONField(default=list)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subscriptions.subscription')),
            ],
        ),
    ]
