# Generated by Django 5.2.4 on 2025-12-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('bonus', 'Bonos'), ('subscription', 'Suscripciones'), ('service', 'Servicios'), ('product', 'Productos'), ('activity', 'Actividades')], max_length=20)),
                ('scope', models.CharField(choices=[('gym', 'Gym'), ('franchise', 'Franchise')], default='gym', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='gyms.franchise')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_categories', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.catalogcategory')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['module', 'scope'], name='catalog_cat_module_a16733_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['gym'], name='catalog_cat_gym_id_f20780_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['franchise'], name='catalog_cat_franchi_cecd24_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcategory',
            constraint=models.UniqueConstraint(fields=('module', 'scope', 'gym', 'franchise', 'name'), name='uniq_catalog_category_module_scope_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='catalogsubcategory',
            index=models.Index(fields=['category'], name='catalog_cat_categor_394785_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_catalog_subcategory_category_name'),
        ),
    ]
