# Generated by Django 5.2.4 on 2025-08-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('gyms', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=120)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('assigned_quantity', models.PositiveIntegerField()),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('signup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('billing_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='clients.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='gyms.gym')),
                ('plan', models.ForeignKey(limit_choices_to={'plan_type': 'bonus'}, on_delete=django.db.models.deletion.PROTECT, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='BonusActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('usage_log', models.JSONField(default=list)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bonuses.bonus')),
            ],
        ),
    ]
