# Generated by Django 5.2.4 on 2025-08-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('bonuses', '0001_initial'),
        ('clients', '0001_initial'),
        ('gyms', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurrent', models.BooleanField(default=False)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('repeat_days', models.CharField(blank=True, help_text="Días de la semana separados por coma: 0=Lun, 6=Dom. Ej: '0,2,4'", max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='gyms.gym')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('staff', models.ManyToManyField(blank=True, related_name='scheduled_sessions', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_late', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('bonus_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonuses.bonus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='scheduler.scheduledsession')),
            ],
        ),
    ]
